apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-demo-3
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tap-demo-3
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/dbuchko/tap-demo-3
      ref:
        branch: main
